import os
import sys

BASE_DIR = getattr(sys, "_MEIPASS", os.path.abspath("."))
BUBBLE_HTML_PATH = os.path.join(BASE_DIR, "bubble.html")

RELAY_SERVER_URL = os.environ.get("RELAY_SERVER_URL", "https://beaver.works")
RELAY_SOCKETIO_PATH = os.environ.get("RELAY_SOCKETIO_PATH", "/socket.io")

STAMP_BALLOON_LIFETIME_SEC = 8.0
STAMP_BALLOON_MIN_SPEED_PX = 90.0
STAMP_BALLOON_MAX_SPEED_PX = 200.0
STAMP_BALLOON_MAX_ACTIVE = 8
STAMP_BALLOON_MAX_WIDTH = 220
STAMP_BALLOON_START_PADDING = 40
STAMP_BALLOON_WOBBLE_AMPLITUDE = 25.0
STAMP_BALLOON_WOBBLE_FREQ_MIN = 0.6
STAMP_BALLOON_WOBBLE_FREQ_MAX = 1.2
STAMP_RECENT_WINDOW_SEC = 20.0
STAMP_DOWNLOAD_TIMEOUT = 10
OVERLAY_TRANSPARENT_COLOR = "#00ff00"
STAMP_ID_CACHE_SIZE = 128
